version: "3"
services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
  prometheus:
      image: prom/prometheus:latest
      ports: ["9090:9090"]
      extra_hosts:
        - "host.docker.internal:host-gateway"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - prom-data:/prometheus
      command:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus

  grafana:
      image: grafana/grafana:latest
      ports: ["3001:3000"]
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
        - grafana_data:/var/lib/grafana
      depends_on: [prometheus]

    
volumes:
  redis_data:
    driver: local
  prom-data:
    driver: local
  grafana_data:
    driver: local